#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Concept Words Dataset Curation Script
======================================
Processes chunk files (chunk_001.json to chunk_034.json) inline according to
docs/prompts/AGENT_WORD_CURATION_PROMPT.md.
Logs every deleted word into res/words/deleted_words.txt in append mode.
"""

import os
import sys
import json
import re
import unicodedata
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple, Set

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

ROOT_DIR = Path(__file__).resolve().parent.parent
RES_DIR = ROOT_DIR / "res"
CHUNKS_DIR = RES_DIR / "words" / "temp_chunks"
DELETED_LOG = RES_DIR / "words" / "deleted_words.txt"

# Ensure deleted words log exists / clean start if desired
DELETED_LOG.parent.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------------------------
# 1. KNOWN DELETIONS (Hallucinations, non-sense, overly specific, touchy)
# ------------------------------------------------------------------------------
KNOWN_EXACT_DELETIONS = {
    # Hallucinations & Non-sense
    "avoir le cœur en orage",
    "avoir le coeur en orage",
    "sequence eclair",
    "sequence eclair (terme medical ?)",
    "la vision de la poussiere",
    "vision de la poussiere",
    "cocaine aux truffes de francois hollande",
    "peau de banane intellectuelle",
    "boule qui-gon (star wars)",
    "boule qui gon (star wars)",
    "boule qui-gon",
    
    # Overly specific / obscure / touchy
    "speeder (star wars)",
    "speeder",
    "casque de dark vador",
    "casque de motocross de tron",
    "le sac de mary poppins",
    "sac de mary poppins",
    "l'interieur du pere noel",
    "interieur du pere noel",
    "l'interieur du pere-noel",
    "le magot de la bande a bonnot",
    "magot de la bande a bonnot",
    "allah",
    "la croix gammee",
    "croix gammee",
    "croix gammée",
    
    # Obscure duplicates / video games / micro-references
    "pandora's box (jeu video)",
    "pandora's box",
}

# Substring or regex patterns that indicate hallucinations or garbage generated by LLM
SUSPICIOUS_DELETE_PATTERNS = [
    re.compile(r"\b(terme médical \?|doublon\?|sur la couleur des mugs)\b", re.IGNORECASE),
    re.compile(r"^cocaine aux truffes", re.IGNORECASE),
    re.compile(r"^la croix gamm[eé]e", re.IGNORECASE),
    re.compile(r"^allah$", re.IGNORECASE),
    re.compile(r"^speeder \(star wars\)", re.IGNORECASE),
    re.compile(r"^casque de (dark vador|motocross de tron)", re.IGNORECASE),
    re.compile(r"^(le )?sac de mary poppins", re.IGNORECASE),
    re.compile(r"^(l['’])?int[eé]rieur du p[eè]re[- ]no[eë]l", re.IGNORECASE),
    re.compile(r"^(le )?magot de la bande [aà] bonnot", re.IGNORECASE),
]

# ------------------------------------------------------------------------------
# 2. KNOWN REWRITES / GENERALIZATIONS
# ------------------------------------------------------------------------------
KNOWN_REWRITES = {
    "pyramide de la haine": "Pyramide de la discrimination et de la violence",
    "ne pas faire une vague": "Ne pas faire de vague",
    "la mer a boire": "C'est pas la mer à boire",
    "la mer à boire": "C'est pas la mer à boire",
    "technological singularity": "Singularité",
    "gpt-4": "ChatGPT",
    "gpt 4": "ChatGPT",
    "la porsche 911": "Porsche",
    "porsche 911": "Porsche",
    "le stop": "Stop",
    "la palette de couleurs": "Palette de couleurs",
    "l'origami": "Origami",
    "le classique": "Classique",
    "le croisement des idées": "Croisement d'idées",
    "le croisement des idees": "Croisement d'idées",
    "le labyrinthe (film)": "Labyrinthe",
    "cordons bleus (garde suisse)": "Cordons bleus",
    "brainstorming (sur la couleur des mugs)": "Brainstorming",
    "fusée (véhicule spatial)": "Fusée",
    "fusee (vehicule spatial)": "Fusée",
    "le trousseau de clés (trousseau ...)": "Trousseau de clés",
    "le trousseau de cles (trousseau ...)": "Trousseau de clés",
    "l'habit ne fait pas le moine (doublon?)": "L'habit ne fait pas le moine",
    "1984 (livre)": "1984",
    "la boîte de pandore (mythologie)": "La Boîte de Pandore",
    "la boîte de pandore (expression)": "La Boîte de Pandore",
    "la boite de pandore (mythologie)": "La Boîte de Pandore",
    "la boite de pandore (expression)": "La Boîte de Pandore",
    "la boîte de vitesses (jeu de mots)": "Boîte de vitesses",
    "la boite de vitesses (jeu de mots)": "Boîte de vitesses",
    "la boîte de vitesses": "Boîte de vitesses",
    "la boite de vitesses": "Boîte de vitesses",
    "la femme de ménage": "Femme de ménage",
    "la femme de menage": "Femme de ménage",
}

# ------------------------------------------------------------------------------
# 3. TITLES / MONUMENTS / PROVERBS / EXPRESSIONS THAT MUST KEEP INITIAL ARTICLES
# ------------------------------------------------------------------------------
KEEP_ARTICLE_PREFIXES = [
    "les fourberies de scapin",
    "le louvre",
    "l'unique exemplaire",
    "la boîte de pandore",
    "la boite de pandore",
    "l'habit ne fait pas le moine",
    "le roi lion",
    "la vénus de milo",
    "la venus de milo",
    "les misérables",
    "les miserables",
    "l'étoile de la mort",
    "l'etoile de la mort",
    "le trône de fer",
    "le trone de fer",
    "le cinquième élément",
    "le cinquieme element",
    "le livre de la jungle",
    "les lettres de mon moulin",
    "la tour de babel",
    "la guerre des boutons",
    "la cerise sur le gâteau",
    "la cerise sur le gateau",
    "la 5ème roue du carrosse",
    "la 5eme roue du carrosse",
    "de la terre à la lune",
    "de la terre a la lune",
    "la fontaine",
    "les liaisons dangereuses",
    "le silence des agneaux",
    "le fabuleux destin d'amélie poulain",
    "le grand bleu",
    "le voyage de chihiro",
    "le bon, la brute et le truand",
    "le parrain",
    "la joconde",
    "le radeau de la méduse",
    "la cène",
    "la nuit étoilée",
    "la grande vadrouille",
    "le petit prince",
    "l'odyssée",
    "l'iliade",
    "le pere noel est une ordure",
    "le père noël est une ordure",
    "le chant des partisans",
    "la marseillaise",
    "la tour eiffel",
    "la statue de la liberté",
    "le mont saint-michel",
    "le colisée",
    "la grande muraille",
    "le taj mahal",
    "le machu picchu",
    "l'everest",
    "le sahara",
    "l'atlantide",
    "l'arche de noé",
    "le saint graal",
    "la fontaine de jouvence",
    "le talon d'achille",
    "le cheval de troie",
    "le fil d'ariane",
    "le complexe d'oedipe",
    "le baiser de judas",
    "l'arbre de noël",
    "la fête des mères",
    "le premier mai",
    "le jour de l'an",
    "le poisson d'avril",
    "la fête de la musique",
    "la saint-valentin",
    "le tour de france",
    "le festival de cannes",
    "la guerre des étoiles",
    "le cercle des poètes disparus",
    "la ligne verte",
    "le sixième sens",
    "le seigneur des anneaux",
    "la cité de la peur",
    "le diner de cons",
    "le dîner de cons",
    "le corbeau et le renard",
    "la cigale et la fourmi",
    "le lièvre et la tortue",
    "le loup et l'agneau",
    "le monstre du loch ness",
    "le yéti",
    "le hollandais volant",
    "le triangle des bermudes",
    "le père noël",
    "la petite souris",
    "le marchand de sable",
    "le roi arthur",
    "la reine des neiges",
    "le chaperon rouge",
    "le petit poucet",
    "la belle au bois dormant",
    "la belle et la bête",
    "le chat botté",
    "le vilain petit canard",
    "le docteur jekyll et mr hyde",
    "le portrait de dorian gray",
    "le fantôme de l'opéra",
    "le joueur d'échecs",
    "le vieil homme et la mer",
    "l'écume des jours",
    "l'étranger",
    "la peste",
    "la métamorphose",
    "le procès",
    "la nuit des temps",
    "la planète des singes",
    "le festin nu",
    "la chartreuse de parme",
    "le rouge et le noir",
    "madame bovary",
    "le comte de monte-cristo",
    "les trois mousquetaires",
    "la guerre et la paix",
    "les fleurs du mal",
    "le spleen de paris",
    "les contemplations",
    "la divine comédie",
    "l'art de la guerre",
    "le prince",
    "le capital",
    "le banquet",
    "l'avare",
    "le malade imaginaire",
    "le tartuffe",
    "le bourgeois gentilhomme",
    "le cid",
    "les fables de la fontaine",
    "le barbier de séville",
    "le mariage de figaro",
    "cyrano de bergerac",
    "en attendant godot",
    "la cantatrice chauve",
    "rhinocéros",
    "huis clos",
]


def strip_accents(s: str) -> str:
    normalized = unicodedata.normalize("NFD", s)
    return "".join(c for c in normalized if unicodedata.category(c) != "Mn")


def clean_display_title(s: str) -> str:
    if not s:
        return ""
    s = unicodedata.normalize("NFKC", s)
    s = s.replace("’", "'").replace("‘", "'").replace("`", "'").replace("´", "'").replace("ʼ", "'")
    s = s.replace("«", '"').replace("»", '"').replace("“", '"').replace("”", '"')
    s = s.replace("—", "-").replace("–", "-").replace("−", "-")
    s = s.replace("\u00a0", " ").replace("\u202f", " ").replace("\u200b", "")
    s = s.strip()
    if (s.startswith('"') and s.endswith('"')) or (s.startswith("'") and s.endswith("'")):
        if len(s) >= 2:
            s = s[1:-1].strip()
    s = re.sub(r"\s+", " ", s).strip()
    return s


def remove_parentheticals(s: str) -> str:
    s = re.sub(r"\([^)]*\)", " ", s)
    s = re.sub(r"\[[^\]]*\]", " ", s)
    s = re.sub(r"\{[^}]*\}", " ", s)
    s = re.sub(r"\s*\([^)]*$", "", s)
    return re.sub(r"\s+", " ", s).strip()


def normalize_comparison_key(s: str, strip_articles: bool = True) -> str:
    s = clean_display_title(s)
    s = remove_parentheticals(s)
    if strip_articles:
        pattern = r"^(l['’]\s*|d['’]\s*|de\s+l['’]\s*|le\s+|la\s+|les\s+|un\s+|une\s+|des\s+|du\s+|de\s+la\s+|the\s+|a\s+|an\s+)"
        s = re.sub(pattern, "", s, flags=re.IGNORECASE).strip()
    s = strip_accents(s.lower())
    return re.sub(r"[^a-z0-9]", "", s)


def should_preserve_article(clean_title: str) -> bool:
    norm = strip_accents(clean_title.lower())
    for prefix in KEEP_ARTICLE_PREFIXES:
        if norm == prefix or norm.startswith(prefix + " ") or norm.startswith(prefix + "'"):
            return True
    return False


def strip_article_if_needed(title: str) -> str:
    if should_preserve_article(title):
        return title
    
    pattern = r"^(L['’]|D['’]|Le\s+|La\s+|Les\s+|Un\s+|Une\s+|Des\s+|Du\s+|De\s+la\s+|The\s+|A\s+|An\s+)"
    match = re.match(pattern, title, flags=re.IGNORECASE)
    if match:
        rest = title[match.end():].strip()
        if rest:
            # Capitalize first letter of stripped term
            return rest[0].upper() + rest[1:]
    return title


def is_entry_deleted(raw_word: str, clean_word: str) -> Tuple[bool, str]:
    raw_norm = strip_accents(raw_word.lower().strip())
    clean_norm = strip_accents(clean_word.lower().strip())
    
    if raw_norm in KNOWN_EXACT_DELETIONS or clean_norm in KNOWN_EXACT_DELETIONS:
        return True, "known_exact_deletion"
        
    for pat in SUSPICIOUS_DELETE_PATTERNS:
        if pat.search(raw_word) or pat.search(clean_word):
            return True, "pattern_match"
            
    # Obscure or meaningless single chars or pure punctuation
    if len(clean_word) <= 1:
        return True, "too_short"
        
    return False, ""


def curate_word_entry(item: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    raw_word = item.get("word", "")
    if not raw_word or not isinstance(raw_word, str):
        return None
        
    # Check known rewrites
    clean_raw = clean_display_title(raw_word)
    norm_raw = strip_accents(clean_raw.lower())
    
    if norm_raw in KNOWN_REWRITES:
        rewritten_word = KNOWN_REWRITES[norm_raw]
    else:
        # Step 1: remove parentheticals
        cleaned = remove_parentheticals(clean_raw)
        # Step 2: strip article for common objects/concepts unless preserved
        rewritten_word = strip_article_if_needed(cleaned)
        
    # Ensure title case / first letter capitalized
    if rewritten_word:
        rewritten_word = rewritten_word[0].upper() + rewritten_word[1:]
        
    # Check deletion
    to_delete, reason = is_entry_deleted(raw_word, rewritten_word)
    if to_delete:
        return None
        
    # Calibrate difficulty 'd'
    d = item.get("d", 1)
    # Common object / animal / basic job -> 0
    # Idioms / proverbs / complex abstract expressions -> 2
    # Check proverbs / expressions
    word_len = len(rewritten_word.split())
    if word_len >= 4:
        # Usually idioms or proverbs
        if d < 1:
            d = 1 if word_len <= 4 else 2
            
    # Ensure c and cc are rounded floats
    c = item.get("c", 0.5)
    cc = item.get("cc", 0.5)
    try:
        c = round(float(c), 2)
        c = max(0.0, min(1.0, c))
    except Exception:
        c = 0.5
        
    try:
        cc = round(float(cc), 2)
        cc = max(0.0, min(1.0, cc))
    except Exception:
        cc = 0.5
        
    # Ensure query_indices
    q_indices = item.get("query_indices", [])
    if isinstance(q_indices, list):
        q_indices = sorted(list(set(int(x) for x in q_indices if 0 <= int(x) <= 169)))
    else:
        q_indices = []
        
    y = item.get("y")
    if y is not None:
        try:
            y = int(y)
        except Exception:
            y = None
            
    return {
        "word": rewritten_word,
        "query_indices": q_indices,
        "y": y,
        "c": c,
        "cc": cc,
        "d": d
    }


def process_chunk(chunk_path: Path) -> Dict[str, Any]:
    with open(chunk_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    chunk_id = data.get("chunk_id", 0)
    total_chunks = data.get("total_chunks", 34)
    words = data.get("words", [])
    
    curated_words = []
    seen_canonical: Dict[str, Dict[str, Any]] = {}
    deleted_in_chunk = []
    
    for item in words:
        raw_word = item.get("word", "")
        curated = curate_word_entry(item)
        if curated is None:
            deleted_in_chunk.append(raw_word)
            continue
            
        canon_key = normalize_comparison_key(curated["word"])
        if canon_key in seen_canonical:
            # Merge query indices
            existing = seen_canonical[canon_key]
            existing["query_indices"] = sorted(list(set(existing["query_indices"] | set(curated["query_indices"]))))
            if existing.get("y") is None and curated.get("y") is not None:
                existing["y"] = curated["y"]
            deleted_in_chunk.append(f"{raw_word} (dedup merged into '{existing['word']}')")
        else:
            seen_canonical[canon_key] = curated
            curated_words.append(curated)
            
    # Append deleted words to DELETED_LOG
    if deleted_in_chunk:
        with open(DELETED_LOG, "a", encoding="utf-8") as df:
            for dw in deleted_in_chunk:
                df.write(f"{dw}\n")
                
    # Update chunk
    data["count"] = len(curated_words)
    data["words"] = curated_words
    
    with open(chunk_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    return {
        "chunk_id": chunk_id,
        "original_count": len(words),
        "curated_count": len(curated_words),
        "deleted_count": len(deleted_in_chunk)
    }


def main():
    chunk_files = sorted(CHUNKS_DIR.glob("chunk_*.json"))
    print(f"🚀 Processing {len(chunk_files)} chunk files inline...")
    
    # Clear deleted log at start of run
    with open(DELETED_LOG, "w", encoding="utf-8") as df:
        df.write("# Liste des mots et entrées supprimés lors de la curation\n")
        
    total_original = 0
    total_curated = 0
    total_deleted = 0
    
    for cfile in chunk_files:
        res = process_chunk(cfile)
        total_original += res["original_count"]
        total_curated += res["curated_count"]
        total_deleted += res["deleted_count"]
        print(f"  • {cfile.name}: {res['original_count']} -> {res['curated_count']} words (-{res['deleted_count']} deleted/merged)")
        
    print(f"\n🎉 Finished curation across all {len(chunk_files)} chunks!")
    print(f"   - Total input words: {total_original:,}")
    print(f"   - Total output words: {total_curated:,}")
    print(f"   - Total deleted / deduplicated: {total_deleted:,}")
    print(f"   - Deleted log saved to: {DELETED_LOG}")


if __name__ == "__main__":
    main()
